SET @FACTURA:=0000000781;
SET @EMPRESA:='APBASE'

UPDATE @EMPRESA.DPDOCCLI SET DOC_MTOIVA=(DOC_BASNET*0.12) 
WHERE DOC_TIPDOC='CON' AND DOC_ESTADO='AC' AND DOC_TIPTRA='D' AND DOC_ACT=1 AND DOC_DOCORG='V' AND `DOC_NUMERO` = @FACTURA;

UPDATE @EMPRESA.DPDOCCLI SET `DOC_NETO`=(DOC_BASNET+DOC_MTOIVA) 
WHERE DOC_TIPDOC='CON' AND DOC_ESTADO='AC' AND DOC_TIPTRA='D' AND DOC_ACT=1 AND DOC_DOCORG='V' AND `DOC_NUMERO` = @FACTURA;

SELECT * FROM @EMPRESA.DPDOCCLI WHERE DOC_TIPDOC='CON' AND `DOC_NUMERO` = @FACTURA LIMIT 99;