SET @FACTURA:=0000000781;
SET @EMPRESA:='APBASE'

# ACTUALIZAR DESDE SUB_CONSULTA
UPDATE @EMPRESA.DPDOCCLI 
SET DOC_BASNET=(SELECT SUM(MOV_TOTAL) FROM @EMPRESA.DPMOVINV WHERE `MOV_DOCUME` = @FACTURA AND `MOV_TIPDOC` = 'CON' GROUP BY MOV_DOCUME) 
WHERE DOC_TIPDOC='CON' AND DOC_ESTADO='AC' AND DOC_TIPTRA='D' AND DOC_ACT=1 AND `DOC_NUMERO` = @FACTURA;

