SET @FACTURA:=0000000781;
SET @EMPRESA:='APBASE'


UPDATE @EMPRESA.DPDOCPRO, @EMPRESA.DPCBTEPAGO
SET DPDOCPRO.DOC_CENCOS=DPCBTEPAGO.PAG_CENCOS
WHERE 
DPDOCPRO.DOC_TIPDOC='ANT' AND 
DPDOCPRO.DOC_CODIGO=DPCBTEPAGO.PAG_CODIGO AND 
DPDOCPRO.DOC_NUMERO=DPCBTEPAGO.PAG_NUMDOC AND
DPDOCPRO.DOC_PAGNUM=DPCBTEPAGO.PAG_NUMERO;

